const tempResults = members.map(m => {
  // ... existing code ...
  const rounded = tempResults.map(r =>
  // ... existing code ...
  // const originalSum = tempResults.reduce((a, b) => a + (typeof b.amount === "number" && b.note !== "特別額" ? Math.round(b.amount) : (typeof b.amount === "number" ? b.amount : 0)), 0); // 未使用のため削除
  // ... existing code ...
}); 